export const TYPES = {
  DbClient: Symbol.for('DbClient'),
  RootRouter: Symbol.for('RootRouter'),
  UserService: Symbol.for('UserService'),
  UserController: Symbol.for('UserController'),
  UserRouter: Symbol.for('UserRouter'),
  UserRepositoryContract: Symbol.for('UserRepositoryContract'),
  GroupOrmRepository: Symbol.for('GroupOrmRepository'),
  GroupService: Symbol.for('GroupService'),
  GroupController: Symbol.for('GroupController'),
  GroupRouter: Symbol.for('GroupRouter'),
  UserGroupOrmRepository: Symbol.for('UserGroupOrmRepository'),
  UserGroupService: Symbol.for('UserGroupService'),
  PhotoOrmRepository: Symbol.for('PhotoOrmRepository'),
  PhotoService: Symbol.for('PhotoService'),
  PhotoController: Symbol.for('PhotoController'),
  LoginService: Symbol.for('LoginService'),
  LoginController: Symbol.for('LoginController'),
  LoginRouter: Symbol.for('LoginRouter'),
  Validator: Symbol.for('Validator')
};
